---
# tasks file for dbserver

- name: Ensure MariaDB server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present
  become: yes

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: Create database {{ db_name }}
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  become: yes

- name: Create database user {{ db_user }} with password
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  become: yes

- name: Copy all .md files to deploy user's home
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ deploy_user }}/"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0644'
  with_fileglob:
    - "{{ deploy_md_files }}"
  become: yes
