---
- hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server and Python dependencies are installed
      ansible.builtin.package:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present

    - name: Ensure MariaDB service is enabled and running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create database webappdb
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create user webappuser with password
      community.mysql.mysql_user:
        name: webappuser
        password: secretpassword
        priv: 'webappdb.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

