---
- hosts: db
  become: true
  vars_files:
    - vars/vault.yml
  tasks:
    - name: Ensure MariaDB-server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB service is enabled and running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create database webappdb
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user webappuser
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ db_password }}"
        priv: "webapp.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

