---
- name: Install and configure UFW on webserver
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow HTTP traffic
      ansible.builtin.command:
        cmd: ufw allow 80/tcp

